### PR TITLE
Add new skin: Dark Plum

### PR DESCRIPTION
**Pull request by Zroxos**
Hi! I made a new skin for Nexus 3. I just found out about the ability to create your own custom skins for the plugin today and I thought it was really exciting. 
This skin that I made is inspired by Nexus 2's Plum skin, used to be one of my favorites :-) I made the entire look more "all-purple"  using different shades of purple colors instead of a black/purple combination.
I inverted the keyboard colors at the bottom to get a look resembling that of some old Pipe Organs with black white keys and white black notes, but with purple shades instead. 
Here's a screenshot: 

Dark Plum for Nexus 3

I kept the [real] tag in the title (not sure what it means) and the reFX copyright header at the top of the file, though I don't know if that's what is preferred.

I've used Nexus for a long time now, and getting my own skin into the plugin would truly be a dream come true. :-) Hope you like it.

### CODE REVIEW

**Comment by reFX-Mike** [comment]
Thanks for this pull-request.

The "real" is supposed to let people know that it uses a "real" (=physical) keyboard and dials, as opposed to a completely flat look.

In my opinion, this skin does not have enough contrast, especially between LCD style components and the background. But also the dials could benefit from less of a gradient.

Would you mind if I take a stab at it? Same concept, but slightly different execution?

**Comment by Zroxos** [comment]
Hey!
I'm glad to hear you like to base idea, please, go ahead! I actually thought about the contrast in the LCD panels myself, it could benefit from a higher contrast.
If you want, I can also send another screenshot of my own take on a higher-contrast LCD panel + less gradient on the dials design. Would you like that? I'm fine with it either way, honestly. :-)

**Comment by reFX-Mike** [comment]
I would prefer if you do the work 😸

**Comment by Zroxos** [comment]
I'm on it! I think this is fun, actually. I'll do my best and send an update. :)

**Comment by reFX-Mike** [comment]
You know that Nexus supports hot-reload, right? So you can make a change to your skin and it immediately gets reloaded without needing to re-start Nexus etc. Just wanted to let you know, in case you aren't aware.

**Comment by Zroxos** [comment]
Yes, I noticed. I'm impressed! Wonderful workflow to have the text editor on top of my DAW in a smaller window next to Nexus and see the changes after every Ctrl + S. Great work on that.

**Comment by Zroxos** [comment]
Hello again!
I made some changes to it. The new look is a bit more "balanced" overall, and the contrast is greater (I just hope it's enough, I can still increase it though). The dials have also been balanced out.
Thoughts? The new one is the top skin, and the old one is at the bottom.

Screenshot 2021-01-12 000213
Screenshot 2021-01-12 000239

**Comment by Zroxos** [comment]
I ended up changing the look so much to fix those issues that it ended up a whole lot different. 
Here's a version based on the original pull request that fixes just the issues you mentioned, the dial gradients and the contrast in the LCD panels. This one keeps the original look and feel that I initially went for.
Let me know what you think. It's not a bother for me to make further changes should that be necessary.
:-)
Screenshot:

Dark Plum for Nexus 3

**Comment by reFX-Mike** [comment]
What do you think about increasing the brightness for the background color just a tiny bit? The individual LCD displays are really hard to make out. At the end of the day, this is a matter of personal taste, of course. Feel free to add yourself as the author in json file. Copyright is still by reFX, because we have to be able to distribute (=copy) it.

**Comment by Zroxos** [comment]
Absolutely. Do you mean the background color that's underneath the dials, and at the edges of the plugin, or do you mean the background color of the LCD panels (where you select the presets)? Just so we're on the same page.
I'll go ahead and add myself as an author there once it's finished!

**Comment by reFX-Mike** [comment]
I mean the color called "background" behind the dials and at the edges of the plugin.

**Comment by Zroxos** [comment]
Wait, I have another question. Apologies for the confusion, but are you referring to brightening the background color of the first screenshot I sent, or in the screenshot of the post I appended afterwards? I don't know if it was clear, but I made 2 different alterations based on your suggestions.
I'm asking since, if I were to brighten the background color of that last screenshot (closest to this post), I would likely have to make the background color brighter than the LCD panels, whereas in the first screenshot I could do more easily what you said, since the background color is already brighter than the LCD panels in that one.
I hope that made sense...

**Comment by reFX-Mike** [comment]
I mean to brighten the one from your newest screenshot.

**Comment by Zroxos** [comment]
I'll try to do that.

**Comment by Zroxos** [comment]
I made the background a bit brighter here. How does it look? It does change the look a little, but at least the LCD panels stand out more now.
Dark Plum for Nexus 3 brighter

**Comment by reFX-Mike** [comment]
Much better. I would remove the gradient colors for the header (and thus the midi-section), so the dials look the same everywhere.

**Comment by Zroxos** [comment]
I've removed that too now. Should I modify the original pull request now with the changes? Are you cool with the way the overall look is now?

**Comment by reFX-Mike** [comment]
You don't need to modify your pull request. It should have all these changes in it already. I might make a few tweaks myself in the coming days before we publish it via the cloud. I hope that's OK.

**Comment by Zroxos** [comment]
I only modified the files locally (they're not connected via git in any way), so I'd need to upload them somehow. I can also make a new pull request altogether, if that's easier.
That's okay. No worries, I saw that the main purple color lost a bit of contrast too after changing the background color, seeing as that was based on a darker background color from earlier.

**Comment by Zroxos** [comment]
There. I updated the branch now, so it has the changes. I added a simple "Made by Zroxos" author thingy at the top. :-)

**Pull request merged**
